#!/usr/bin/env node
"use strict";

// context-index.js — keep AGENTS.md small while indexing project context.
// Usage:
//   node scripts/context-index.js update
//   node scripts/context-index.js list
//   node scripts/context-index.js query "term"
//   node scripts/context-index.js section "Operating Constraints"
//   node scripts/context-index.js stats
//   node scripts/context-index.js hydrate "current task"
//   node scripts/context-index.js check

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const {
  ensureDir,
  findProjectRoot,
  readJSONSafe,
  readSection,
  readTextSafe,
  writeJson,
} = require("./lib");

const START = "<!-- context-harness:index:start -->";
const END = "<!-- context-harness:index:end -->";
const LIBRARY_SCHEMA = 1;
const LARGE_SECTION_LINES = 80;
const LARGE_SECTION_CHARS = 3000;
const ALWAYS_READ_CONTEXT_LINES = 120;
const ALWAYS_READ_CONTEXT_CHARS = 6000;
const HYDRATE_LIMIT = 7;
const STOP_WORDS = new Set([
  "a",
  "an",
  "and",
  "are",
  "as",
  "at",
  "be",
  "by",
  "context",
  "for",
  "current",
  "from",
  "harness",
  "how",
  "improve",
  "improvement",
  "in",
  "into",
  "is",
  "it",
  "of",
  "on",
  "or",
  "that",
  "the",
  "task",
  "this",
  "to",
  "work",
  "working",
  "with",
]);

const PURPOSES = {
  Project: "identity and purpose",
  Structure: "repo map",
  "Operating Constraints": "project-specific constraints that change agent decisions",
  Workflow: "setup, run, test, lint, deploy",
  Language: "canonical terms",
  Relationships: "durable invariants",
  "Flagged Ambiguities": "resolved meaning conflicts",
  "Learned Patterns": "durable lessons",
};

const command = process.argv[2] || "update";
const arg = process.argv.slice(3).join(" ").trim();
const root = findProjectRoot(process.cwd());
const contextFile = path.join(root, "CONTEXT.md");
const agentsFile = path.join(root, "AGENTS.md");
const libraryDir = path.join(root, ".context-harness");
const indexFile = path.join(libraryDir, "index.json");
const cardsDir = path.join(libraryDir, "cards");
const chunksDir = path.join(libraryDir, "chunks");

main();

function main() {
  const context = readTextSafe(contextFile);
  if (!context) {
    console.error("CONTEXT.md not found.");
    process.exit(1);
  }

  if (command === "update") {
    updateAgents(context);
    return;
  }

  if (command === "list") {
    process.stdout.write(renderIndex(context));
    return;
  }

  if (command === "section") {
    printSection(context, arg);
    return;
  }

  if (command === "query") {
    queryIndex(context, arg);
    return;
  }

  if (command === "stats") {
    printStats(context);
    return;
  }

  if (command === "hydrate") {
    hydrateContext(context, arg);
    return;
  }

  if (command === "check") {
    checkHarness(context);
    return;
  }

  console.error("Usage: node scripts/context-index.js [update|list|query|section|stats|hydrate|check] [text]");
  process.exit(1);
}

function updateAgents(context) {
  writeContextLibrary(context);
  const current = readTextSafe(agentsFile) || defaultAgents();
  const block = renderIndex(context).trimEnd();
  const next = replaceManagedBlock(current, block);
  fs.writeFileSync(agentsFile, `${next.trimEnd()}\n`);
  console.log(`Updated ${path.relative(root, agentsFile)} and .context-harness/index.json from context files.`);
}

function renderIndex(context) {
  const sections = parseSections(context).filter((section) => section.level === 2);
  const lines = [
    "## Context Index",
    START,
    "Generated by `node scripts/context-index.js update`; keep `CONTEXT.md` small enough to read with `NOW.md`.",
    "Use `node scripts/context-index.js hydrate \"<task>\"` to select cards before opening `PLAN.md`, chunks, or bulky sections.",
    "",
    "- `NOW.md` - read first on start/resume.",
    "- `CONTEXT.md` - read directly while it remains concise; compact it when it stops fitting the always-read layer.",
    "- `.context-harness/index.json` - machine retrieval manifest; do not read wholesale.",
  ];

  for (const section of sections) {
    const childText = section.children.length
      ? ` Sub: ${section.children.map((child) => child.title).join(", ")}.`
      : "";
    lines.push(`- \`CONTEXT.md#${section.anchor}\` - ${describeSection(context, section)}.${childText}`);
  }

  lines.push(END);
  return `${lines.join("\n")}\n`;
}

function replaceManagedBlock(text, block) {
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start !== -1 && end !== -1 && end > start) {
    const prefix = text.slice(0, start);
    const headingMatch = prefix.match(/(?:^|\n)(?:## Context Index\s*\n\s*)+$/u);
    const replaceStart = headingMatch
      ? prefix.length - headingMatch[0].length + (headingMatch[0].startsWith("\n") ? 1 : 0)
      : start;
    const before = text.slice(0, replaceStart).replace(/[ \t]*$/u, "");
    const after = text.slice(end + END.length).replace(/^\s*/u, "\n");
    return `${before}${block}${after}`;
  }
  return `${text.trimEnd()}\n\n${block}`;
}

function defaultAgents() {
  return `# Agent Instructions
<!-- context-harness:schema v3 -->

## Context Contract
- At session start/resume, read \`NOW.md\` first and read concise \`CONTEXT.md\` as the always-read project layer.
- Use \`node scripts/context-index.js hydrate "<task>"\` before opening \`PLAN.md\`, chunks, or bulky/task-specific context.
- Keep \`CONTEXT.md\` small; if it no longer fits the always-read layer, use hydrate-selected cards/sections and compact it.
- Before planning or editing, respect \`CONTEXT.md\` \`## Operating Constraints\`.
- If context-harness files or generated indexes look stale, note that as a follow-up unless it blocks the user task; do not let harness maintenance replace the requested work.
- If the user teaches a durable term, invariant, workflow, constraint, or
  correction, update \`CONTEXT.md\` before it scrolls away.
- Route task-local findings and decisions to \`PLAN.md\`; durable lessons to
  \`CONTEXT.md\`.
- After updating \`CONTEXT.md\`, \`PLAN.md\`, or \`NOW.md\`, run \`node scripts/context-index.js update\` when the change should affect future retrieval.
- Before ending, update \`NOW.md\` with current focus, blockers, next step, and
  touched files.
`;
}

function checkHarness(context) {
  const failures = [];
  const warnings = [];
  const agents = readTextSafe(agentsFile);
  const now = readTextSafe(path.join(root, "NOW.md"));
  const plan = readTextSafe(path.join(root, "PLAN.md"));

  const requiredSections = [
    "Project",
    "Structure",
    "Workflow",
    "Language",
    "Relationships",
    "Flagged Ambiguities",
    "Learned Patterns",
  ];

  if (!hasSchema(context)) failures.push("CONTEXT.md must use context-harness schema v3.");

  if (!agents.trim()) failures.push("AGENTS.md is missing.");
  else if (!hasSchema(agents)) failures.push("AGENTS.md must use context-harness schema v3.");

  if (agents.trim()) {
    const agentLines = agents.trimEnd().split("\n").length;
    const nonIndex = stripIndex(agents);
    if (agentLines > 80) {
      warnings.push(`AGENTS.md has ${agentLines} lines; keep it to the Context Contract plus generated Context Index.`);
    }
    if (looksLikeDetailedOperatingBrief(nonIndex)) {
      warnings.push("AGENTS.md appears to contain durable operating context; move project facts to CONTEXT.md.");
    }
  }

  for (const heading of requiredSections) {
    if (!hasHeading(context, 2, heading)) failures.push(`CONTEXT.md is missing ## ${heading}.`);
  }
  if (!hasHeading(context, 2, "Operating Constraints")) {
    failures.push("CONTEXT.md is missing ## Operating Constraints.");
  }

  if (agents.trim()) {
    if (!agents.includes(START) || !agents.includes(END)) {
      failures.push("AGENTS.md is missing the generated Context Index block.");
    } else if (!indexIsFresh(agents, context)) {
      failures.push("AGENTS.md Context Index is stale; run `node scripts/context-index.js update`.");
    }
  }

  checkLibraryFresh(context, failures, warnings);

  if (now.trim()) {
    const nowLines = now.trimEnd().split("\n").length;
    if (nowLines > 20) warnings.push(`NOW.md has ${nowLines} lines; consider a Dream/Compact pass.`);
  }

  if (plan.trim()) {
    const planLines = plan.trimEnd().split("\n").length;
    if (planLines > 150) warnings.push(`PLAN.md has ${planLines} lines; consider a Dream/Compact pass.`);
  }

  for (const warning of warnings) console.log(`WARN ${warning}`);
  if (failures.length) {
    for (const failure of failures) console.log(`FAIL ${failure}`);
    process.exit(1);
  }
  console.log("OK context-harness check passed.");
}

function hasSchema(text) {
  return /<!--\s*context-harness:schema\s+v3\s*-->/.test(text);
}

function stripIndex(text) {
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start === -1 || end === -1 || end <= start) return text;
  return `${text.slice(0, start)}${text.slice(end + END.length)}`;
}

function looksLikeDetailedOperatingBrief(text) {
  const durableHeadings = [
    "Current Status",
    "Project Mission",
    "Near-Term Priorities",
    "Guiding Principles",
    "High-Level Timeline",
    "Communication Style",
    "Reusable Templates",
    "Recent Key Achievements",
  ];
  const headingHits = durableHeadings.filter((heading) => hasHeading(text, 2, heading) || hasHeading(text, 3, heading)).length;
  if (headingHits >= 2) return true;

  return /detailed durable project context remains in `?AGENTS\.md`?/i.test(text)
    || /AGENTS\.md.*(detailed|primary).*operating/i.test(text)
    || /comprehensive context for AI agents/i.test(text);
}

function hasHeading(markdown, level, heading) {
  const hashes = "#".repeat(level);
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`^${hashes}\\s+${escaped}\\s*$`, "m").test(markdown);
}

function indexIsFresh(agents, context) {
  const expected = renderIndex(context).trim();
  const start = agents.indexOf(START);
  const end = agents.indexOf(END);
  if (start === -1 || end === -1 || end <= start) return false;
  const headingStart = agents.lastIndexOf("## Context Index", start);
  const actualStart = headingStart === -1 ? start : headingStart;
  const actual = agents.slice(actualStart, end + END.length).trim();
  return actual === expected;
}

function checkLibraryFresh(context, failures, warnings) {
  const libraryExists = fs.existsSync(indexFile) || fs.existsSync(cardsDir) || fs.existsSync(chunksDir);
  if (!libraryExists) return;

  const manifest = readJSONSafe(indexFile);
  if (!manifest) {
    failures.push(".context-harness/index.json is missing or invalid; run `node scripts/context-index.js update`.");
    return;
  }

  if (manifest.schema !== LIBRARY_SCHEMA) warnings.push(".context-harness/index.json uses an unknown schema version.");
  const expectedHash = sourceHash(readSourceFiles(context));
  if (manifest.source_hash !== expectedHash) {
    failures.push(".context-harness/index.json is stale; run `node scripts/context-index.js update`.");
  }

  for (const card of manifest.cards || []) {
    if (card.card_path && !fs.existsSync(path.join(root, card.card_path))) {
      failures.push(`Missing context card ${card.card_path}; run \`node scripts/context-index.js update\`.`);
      break;
    }
    if (card.chunk_path && !fs.existsSync(path.join(root, card.chunk_path))) {
      failures.push(`Missing context chunk ${card.chunk_path}; run \`node scripts/context-index.js update\`.`);
      break;
    }
  }
}

function parseSections(context) {
  const sections = [];
  let currentH2 = null;
  for (const line of context.split("\n")) {
    const match = line.match(/^(##|###)\s+(.+?)\s*$/u);
    if (!match) continue;
    const section = {
      level: match[1].length,
      title: match[2].replace(/`/g, ""),
      anchor: anchorFor(match[2]),
      children: [],
    };
    if (section.level === 2) {
      sections.push(section);
      currentH2 = section;
    } else if (section.level === 3 && currentH2) {
      currentH2.children.push(section);
      sections.push(section);
    }
  }
  return sections;
}

function parseTopSections(markdown, file) {
  const lines = markdown.split("\n");
  const sections = [];
  let current = null;

  for (let i = 0; i < lines.length; i += 1) {
    const match = lines[i].match(/^(##)\s+(.+?)\s*$/u);
    if (!match) continue;
    if (current) {
      current.endLine = i;
      current.body = lines.slice(current.bodyStartIndex, i).join("\n").trimEnd();
      sections.push(current);
    }
    const title = match[2].replace(/`/g, "");
    current = {
      file,
      level: 2,
      title,
      anchor: uniqueAnchor(title, sections),
      startLine: i + 2,
      bodyStartIndex: i + 1,
      endLine: lines.length,
      body: "",
      children: [],
    };
  }

  if (current) {
    current.body = lines.slice(current.bodyStartIndex).join("\n").trimEnd();
    sections.push(current);
  }

  return sections.map((section) => ({
    ...section,
    lineCount: countLines(section.body),
    charCount: section.body.length,
    children: childHeadings(section.body),
  }));
}

function childHeadings(body) {
  return body
    .split("\n")
    .map((line) => line.match(/^###\s+(.+?)\s*$/u))
    .filter(Boolean)
    .map((match) => match[1].replace(/`/g, ""));
}

function describeSection(context, section) {
  if (PURPOSES[section.title]) return PURPOSES[section.title];
  const body = readSection(context, section.title);
  const first = body
    .split("\n")
    .map((line) => line.trim())
    .find((line) => line && !line.startsWith("<!--") && !line.startsWith("```"));
  return first ? truncate(cleanMarkdown(first), 90) : "context section";
}

function printSection(context, heading) {
  if (!heading) {
    console.error("Provide a section heading.");
    process.exit(1);
  }
  const body = readSection(context, heading);
  if (!body.trim()) {
    console.error(`Section not found: ${heading}`);
    process.exit(1);
  }
  process.stdout.write(`## ${heading}\n${body.trimEnd()}\n`);
}

function queryIndex(context, query) {
  const terms = parseTerms(query);
  if (!terms.length) {
    console.error("Provide a query term.");
    process.exit(1);
  }

  const matches = parseSections(context)
    .filter((section) => section.level === 2)
    .map((section) => {
      const body = readSection(context, section.title);
      const haystack = `${section.title}\n${body}`.toLowerCase();
      return { section, body, hit: terms.every((term) => haystack.includes(term)) };
    })
    .filter((entry) => entry.hit);

  if (!matches.length) {
    console.log("No matching CONTEXT.md sections.");
    return;
  }

  for (const { section, body } of matches) {
    console.log(`- CONTEXT.md#${section.anchor} (${section.title})`);
    const snippet = body
      .split("\n")
      .map((line) => cleanMarkdown(line.trim()))
      .find((line) => line && terms.some((term) => line.toLowerCase().includes(term)));
    if (snippet) console.log(`  ${truncate(snippet, 120)}`);
  }
}

function printStats(context) {
  const stats = buildStats(context);
  console.log("Context Harness Stats");
  console.log("");
  console.log("Files:");
  for (const file of stats.files) {
    console.log(`- ${file.path}: ${file.lines} lines${file.exists ? "" : " (missing)"}`);
  }
  console.log("");
  console.log("Largest sections:");
  for (const section of stats.largestSections.slice(0, 8)) {
    console.log(`- ${section.source}: ${section.lines} lines, ~${section.tokens_est} tokens`);
  }
  console.log("");
  console.log("Context library:");
  console.log(`- manifest: ${stats.library.hasIndex ? ".context-harness/index.json" : "missing"}`);
  console.log(`- cards: ${stats.library.cards}`);
  console.log(`- chunks: ${stats.library.chunks}`);
  if (stats.warnings.length) {
    console.log("");
    console.log("Warnings:");
    for (const warning of stats.warnings) console.log(`- ${warning}`);
  }
}

function hydrateContext(context, query) {
  const terms = parseTerms(query);
  if (!terms.length) {
    console.error("Provide a task or query to hydrate.");
    process.exit(1);
  }

  const library = readFreshLibrary(context);
  const scored = library.cards
    .map((card) => ({ card, ...scoreCard(card, terms) }))
    .filter((entry) => entry.matched)
    .sort((a, b) => b.score - a.score || b.card.importance - a.card.importance || a.card.id.localeCompare(b.card.id));

  const selected = (scored.length ? scored : library.cards.map((card) => ({ card, score: card.importance, matched: false })))
    .slice(0, HYDRATE_LIMIT);

  if (!selected.length) {
    console.log("No context cards available. Read `NOW.md` and concise `CONTEXT.md`; run `node scripts/context-index.js update` when context sources exist.");
    return;
  }

  const contextPolicy = contextSizePolicy(context);
  const totalTokens = selected.reduce((sum, entry) => sum + (entry.card.tokens_est || 0), 0);
  console.log(`Hydrated context for: ${query}`);
  if (library.stale) console.log("WARN .context-harness/index.json is stale; selected cards are computed from current markdown, but generated card files may be stale. Use the source sections below or run `node scripts/context-index.js update` before opening card files.");
  console.log(`Cards: ${selected.length}; estimated raw tokens if fully opened: ~${totalTokens}`);
  console.log("");

  console.log("Always-read layer:");
  console.log("- Read `NOW.md` first.");
  console.log(contextPolicy.alwaysRead
    ? `- Read concise \`CONTEXT.md\` directly (${contextPolicy.lines} lines, ~${contextPolicy.chars} chars).`
    : `- \`CONTEXT.md\` is beyond the always-read budget (${contextPolicy.lines} lines, ~${contextPolicy.chars} chars); use selected cards/sections before opening it wholesale.`);
  console.log("");

  console.log("Open first for progressive detail:");
  selected.forEach(({ card, score }, index) => {
    console.log(`${index + 1}. ${card.id} (${card.title})`);
    console.log(`   score: ${score.toFixed(2)}; source: ${card.source}`);
    console.log(`   why: ${readableMatchReason(card, terms)}`);
    console.log(`   summary: ${card.summary}`);
    if (card.key_facts?.length) {
      console.log("   key facts:");
      for (const fact of card.key_facts.slice(0, 3)) console.log(`   - ${fact}`);
    }
    if (library.stale) console.log(`   source section: ${card.source}`);
    else console.log(`   open card: ${card.card_path}`);
  });
  console.log("");

  const deferred = selected.filter((entry) => entry.card.chunk_path || entry.card.source);
  console.log("Open next only if needed:");
  for (const { card } of deferred) {
    console.log(`- ${card.source}`);
    if (card.chunk_path) console.log(`  raw detail on demand: ${card.chunk_path}`);
  }
  console.log("");

  console.log("Retrieval evidence:");
  console.log(`- hydrate_query: ${query}`);
  console.log(`- always_read_context: ${contextPolicy.alwaysRead ? "CONTEXT.md" : "selected cards before full CONTEXT.md"}`);
  console.log(`- context_size_policy: ${contextPolicy.reason}`);
  console.log(`- selected_cards: ${selected.map((entry) => entry.card.id).join(", ")}`);
  console.log(`- raw_sources_deferred: ${deferred.length ? "true" : "false"}`);
}

function contextSizePolicy(context) {
  const lines = countLines(context);
  const chars = context.length;
  const alwaysRead = lines <= ALWAYS_READ_CONTEXT_LINES && chars <= ALWAYS_READ_CONTEXT_CHARS;
  return {
    lines,
    chars,
    alwaysRead,
    reason: alwaysRead
      ? `CONTEXT.md fits always-read budget (${ALWAYS_READ_CONTEXT_LINES} lines / ${ALWAYS_READ_CONTEXT_CHARS} chars)`
      : `CONTEXT.md exceeds always-read budget (${ALWAYS_READ_CONTEXT_LINES} lines / ${ALWAYS_READ_CONTEXT_CHARS} chars)`,
  };
}

function readableMatchReason(card, terms) {
  const haystacks = [card.title, card.summary, card.source, ...(card.tags || []), ...(card.read_when || []), ...(card.key_facts || [])]
    .map((value) => normalizeForSearch(value));
  const matched = terms.filter((term) => haystacks.some((haystack) => haystack.includes(term))).slice(0, 5);
  if (matched.length) return `matched ${matched.join(", ")}`;
  return `fallback by importance ${card.importance}`;
}

function writeContextLibrary(context) {
  const library = buildLibrary(context);
  ensureDir(cardsDir);
  ensureDir(chunksDir);

  const expectedCards = new Set();
  const expectedChunks = new Set();

  for (const card of library.cards) {
    const absoluteCardPath = path.join(root, card.card_path);
    expectedCards.add(absoluteCardPath);
    ensureDir(path.dirname(absoluteCardPath));
    fs.writeFileSync(absoluteCardPath, renderCard(card));

    if (card.chunk_path) {
      const absoluteChunkPath = path.join(root, card.chunk_path);
      expectedChunks.add(absoluteChunkPath);
      ensureDir(path.dirname(absoluteChunkPath));
      fs.writeFileSync(absoluteChunkPath, `${card.raw.trimEnd()}\n`);
    }
    delete card.raw;
  }

  pruneGeneratedMarkdown(cardsDir, expectedCards);
  pruneGeneratedMarkdown(chunksDir, expectedChunks);
  writeJson(indexFile, { ...library, cards: library.cards.map(({ raw, ...card }) => card) });
}

function readFreshLibrary(context) {
  const sourceFiles = readSourceFiles(context);
  const expectedHash = sourceHash(sourceFiles);
  const manifest = readJSONSafe(indexFile);
  if (manifest && manifest.schema === LIBRARY_SCHEMA && manifest.source_hash === expectedHash && Array.isArray(manifest.cards)) {
    return { ...manifest, stale: false };
  }
  return { ...buildLibrary(context), stale: Boolean(manifest) };
}

function buildLibrary(context) {
  const sourceFiles = readSourceFiles(context);
  const cards = [];

  for (const source of sourceFiles) {
    if (!source.text.trim()) continue;
    for (const section of contextUnits(source)) {
      if (!section.body.trim()) continue;
      cards.push(buildCard(section));
    }
  }

  return {
    schema: LIBRARY_SCHEMA,
    updated_at: newestSourceMtimeISO(sourceFiles),
    source_hash: sourceHash(sourceFiles),
    sources: sourceFiles.map((source) => ({ path: source.path, sha256: sha256(source.text), lines: countLines(source.text) })),
    cards,
  };
}

function buildCard(section) {
  const sourceStem = slug(path.basename(section.file, ".md"));
  const id = `ctx-${sourceStem}-${slug(section.anchor || section.title)}`;
  const source = `${section.file}${section.anchor ? `#${section.anchor}` : ""}`;
  const summary = summarize(section.title, section.body);
  const keyFacts = extractKeyFacts(section.body);
  const needsChunk = section.lineCount > LARGE_SECTION_LINES || section.charCount > LARGE_SECTION_CHARS;
  const chunkPath = needsChunk ? `.context-harness/chunks/${id}.md` : "";

  return {
    id,
    title: `${section.file}: ${section.title}`,
    summary,
    source,
    source_path: section.file,
    kind: classifyKind(section.file, section.title),
    scope: section.file === "CONTEXT.md" ? "project" : "task",
    importance: importanceFor(section),
    confidence: "confirmed",
    recency: newestMtimeISO([path.join(root, section.file)]),
    tokens_est: estimateTokens(section.body),
    tags: tagsFor(section),
    read_when: readWhenFor(section),
    card_path: `.context-harness/cards/${id}.md`,
    chunk_path: chunkPath,
    content_sha256: sha256(section.body),
    key_facts: keyFacts,
    raw: `# ${section.title}\n\n${section.body.trimEnd()}`,
  };
}

function renderCard(card) {
  const lines = [
    "---",
    `id: ${card.id}`,
    `kind: ${card.kind}`,
    `importance: ${card.importance}`,
    `confidence: ${card.confidence}`,
    `source: ${card.source}`,
    card.chunk_path ? `chunk: ${card.chunk_path}` : "chunk: null",
    `tokens_est: ${card.tokens_est}`,
    `tags: [${card.tags.join(", ")}]`,
    "---",
    "",
    `# ${card.title}`,
    "",
    "## Summary",
    card.summary,
    "",
    "## Use when",
    ...card.read_when.map((item) => `- ${item}`),
    "",
    "## Key facts",
    ...(card.key_facts.length ? card.key_facts.map((fact) => `- ${fact}`) : ["- Use this card before opening bulky raw context for this topic."]),
    "",
    "## Retrieval order",
    "- Read `NOW.md` and concise `CONTEXT.md` as the always-read layer.",
    "- Use this card before opening bulky `PLAN.md`, chunks, or raw source sections for this topic.",
    "- Open raw detail only when this summary is insufficient for the task.",
    "",
    "## Open next only if needed",
    `- \`${card.source}\``,
  ];
  if (card.chunk_path) lines.push(`- \`${card.chunk_path}\``);
  return `${lines.join("\n")}\n`;
}

function readSourceFiles(context) {
  return [
    { path: "CONTEXT.md", text: context },
    { path: "NOW.md", text: readTextSafe(path.join(root, "NOW.md")) },
    { path: "PLAN.md", text: readTextSafe(path.join(root, "PLAN.md")) },
  ].filter((source) => source.text.trim());
}

function contextUnits(source) {
  if (source.path === "NOW.md") {
    return [{ file: source.path, title: "Now", anchor: "now", body: source.text, lineCount: countLines(source.text), charCount: source.text.length }];
  }

  const sections = parseTopSections(source.text, source.path);
  if (sections.length) return sections;
  return [{ file: source.path, title: path.basename(source.path, ".md"), anchor: slug(source.path), body: source.text, lineCount: countLines(source.text), charCount: source.text.length }];
}

function buildStats(context) {
  const files = ["AGENTS.md", "CONTEXT.md", "NOW.md", "PLAN.md"].map((relative) => {
    const text = relative === "CONTEXT.md" ? context : readTextSafe(path.join(root, relative));
    return { path: relative, exists: Boolean(text), lines: text ? countLines(text) : 0 };
  });
  const sourceFiles = readSourceFiles(context);
  const sections = sourceFiles.flatMap((source) => contextUnits(source).map((section) => ({
    source: `${section.file}${section.anchor ? `#${section.anchor}` : ""}`,
    lines: section.lineCount,
    tokens_est: estimateTokens(section.body),
  })));

  const warnings = [];
  const now = files.find((file) => file.path === "NOW.md");
  const plan = files.find((file) => file.path === "PLAN.md");
  const agents = files.find((file) => file.path === "AGENTS.md");
  if (now && now.lines > 20) warnings.push(`NOW.md has ${now.lines} lines; consider Dream consolidation.`);
  if (plan && plan.lines > 150) warnings.push(`PLAN.md has ${plan.lines} lines; consider Dream consolidation.`);
  if (agents && agents.lines > 80) warnings.push(`AGENTS.md has ${agents.lines} lines; keep startup context small.`);
  for (const section of sections) {
    if (section.lines > LARGE_SECTION_LINES) warnings.push(`${section.source} has ${section.lines} lines; consider a context card/chunk pointer.`);
  }

  return {
    files,
    largestSections: sections.sort((a, b) => b.lines - a.lines),
    library: {
      hasIndex: fs.existsSync(indexFile),
      cards: countFiles(cardsDir, ".md"),
      chunks: countFiles(chunksDir, ".md"),
    },
    warnings,
  };
}

function scoreCard(card, terms) {
  const title = normalizeForSearch(card.title);
  const summary = normalizeForSearch(card.summary);
  const tags = normalizeForSearch((card.tags || []).join(" "));
  const readWhen = normalizeForSearch((card.read_when || []).join(" "));
  const source = normalizeForSearch(card.source);
  const keyFacts = normalizeForSearch((card.key_facts || []).join(" "));
  const haystack = `${title} ${summary} ${tags} ${readWhen} ${source} ${keyFacts}`;
  let lexicalScore = 0;
  for (const term of terms) {
    if (title.includes(term)) lexicalScore += 4;
    if (tags.includes(term)) lexicalScore += 3;
    if (readWhen.includes(term)) lexicalScore += 2;
    if (summary.includes(term)) lexicalScore += 2;
    if (keyFacts.includes(term)) lexicalScore += 2;
    if (source.includes(term)) lexicalScore += 1;
  }
  if (terms.every((term) => haystack.includes(term))) lexicalScore += 2;
  return {
    matched: lexicalScore > 0,
    score: lexicalScore + (card.importance || 0),
  };
}

function summarize(title, body) {
  const explicit = cleanLines(body).find((line) => !/^#+\s/u.test(line));
  if (explicit) return truncate(cleanMarkdown(explicit), 220);
  if (PURPOSES[title]) return PURPOSES[title];
  return `Context for ${title}.`;
}

function extractKeyFacts(body) {
  return cleanLines(body)
    .map(cleanMarkdown)
    .filter((line) => line && !line.startsWith("#"))
    .slice(0, 5)
    .map((line) => truncate(line, 160));
}

function cleanLines(body) {
  return body
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("<!--") && !line.startsWith("```"));
}

function classifyKind(file, title) {
  if (file === "NOW.md") return "resume";
  if (file === "PLAN.md") return "plan";
  const normalized = title.toLowerCase();
  if (normalized.includes("constraint")) return "constraints";
  if (normalized.includes("rule")) return "rules";
  if (normalized.includes("workflow")) return "workflow";
  if (normalized.includes("language")) return "language";
  if (normalized.includes("relationship")) return "invariant";
  if (normalized.includes("pattern")) return "lesson";
  if (normalized.includes("project")) return "project";
  return "context";
}

function importanceFor(section) {
  if (section.file === "NOW.md") return 0.95;
  if (section.file === "PLAN.md") return 0.85;
  if (["Operating Constraints", "Workflow"].includes(section.title)) return 0.9;
  if (["Language", "Relationships"].includes(section.title)) return 0.82;
  if (section.title === "Learned Patterns") return 0.78;
  if (section.lineCount > LARGE_SECTION_LINES || section.charCount > LARGE_SECTION_CHARS) return 0.74;
  return 0.65;
}

function tagsFor(section) {
  const tags = new Set([slug(path.basename(section.file, ".md")), slug(section.title), classifyKind(section.file, section.title)]);
  for (const child of section.children || []) tags.add(slug(child));
  return [...tags].filter(Boolean);
}

function readWhenFor(section) {
  if (section.file === "NOW.md") return ["resuming the current session", "choosing the immediate next step", "update context after current work"];
  if (section.file === "PLAN.md") return ["continuing the active task", "checking done criteria or decisions", "update context with task-local progress"];
  if (section.title === "Operating Constraints") return ["before planning or editing", "checking project constraints", "update context safely"];
  if (section.title === "Workflow") return ["running, testing, linting, deploying, deployment, or verifying changes"];
  if (section.title === "Language") return ["using project terms or resolving naming ambiguity", "update context terminology"];
  if (section.title === "Relationships") return ["changing architecture or domain relationships", "update context invariants"];
  if (section.title === "Learned Patterns") return ["avoiding repeated mistakes or applying prior corrections", "update context with durable lessons"];
  return [`working on ${section.title.toLowerCase()}`];
}

function sourceHash(sourceFiles) {
  return sha256(sourceFiles.map((source) => `${source.path}\n${source.text}`).join("\n---context-source---\n"));
}

function newestMtimeISO(files) {
  let newest = 0;
  for (const file of files) {
    try {
      newest = Math.max(newest, fs.statSync(file).mtimeMs);
    } catch {
      // ignore missing source files
    }
  }
  return newest ? new Date(newest).toISOString().slice(0, 10) : "unknown";
}

function countFiles(dir, extension) {
  try {
    return fs.readdirSync(dir).filter((file) => file.endsWith(extension)).length;
  } catch {
    return 0;
  }
}

function countLines(text) {
  if (!text) return 0;
  return text.trimEnd() ? text.trimEnd().split("\n").length : 0;
}

function estimateTokens(text) {
  return Math.max(1, Math.ceil((text || "").length / 4));
}

function parseTerms(query) {
  const terms = normalizeForSearch(query)
    .split(/\s+/u)
    .map((term) => term.trim())
    .filter(Boolean);
  const filtered = terms.filter((term) => !STOP_WORDS.has(term));
  return filtered.length ? filtered : terms;
}

function normalizeForSearch(text) {
  return String(text || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/gu, " ")
    .trim();
}

function pruneGeneratedMarkdown(dir, expectedFiles) {
  let files = [];
  try {
    files = fs.readdirSync(dir);
  } catch {
    return;
  }
  for (const file of files) {
    if (!file.endsWith(".md")) continue;
    const absolute = path.join(dir, file);
    if (!expectedFiles.has(absolute)) fs.unlinkSync(absolute);
  }
}

function newestSourceMtimeISO(sourceFiles) {
  const files = sourceFiles.map((source) => path.join(root, source.path));
  return newestMtimeISO(files);
}

function uniqueAnchor(title, existingSections) {
  const base = anchorFor(title);
  const duplicateCount = existingSections.filter((section) => section.anchor === base || section.anchor.startsWith(`${base}-`)).length;
  return duplicateCount ? `${base}-${duplicateCount}` : base;
}

function anchorFor(title) {
  return title
    .toLowerCase()
    .replace(/`/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function slug(text) {
  return anchorFor(String(text || "context")) || "context";
}

function cleanMarkdown(line) {
  return line
    .replace(/^[-*]\s+/u, "")
    .replace(/^\d+\.\s+/u, "")
    .replace(/[`*_]/g, "")
    .trim();
}

function truncate(text, max) {
  if (text.length <= max) return text;
  return `${text.slice(0, max - 3).trimEnd()}...`;
}

function sha256(text) {
  return crypto.createHash("sha256").update(text).digest("hex");
}
