#!/usr/bin/env node
"use strict";

// context-index.js — keep AGENTS.md small while indexing CONTEXT.md.
// Usage:
//   node scripts/context-index.js update
//   node scripts/context-index.js list
//   node scripts/context-index.js query "term"
//   node scripts/context-index.js section "Rules"
//   node scripts/context-index.js check

const fs = require("fs");
const path = require("path");
const { findProjectRoot, readSection, readTextSafe } = require("./lib");

const START = "<!-- context-harness:index:start -->";
const END = "<!-- context-harness:index:end -->";

const PURPOSES = {
  Project: "identity and purpose",
  Structure: "repo map",
  Rules: "constraints and habits",
  Workflow: "setup, run, test, lint, deploy",
  Language: "canonical terms",
  Relationships: "durable invariants",
  "Flagged Ambiguities": "resolved meaning conflicts",
  "Learned Patterns": "durable lessons",
};

const command = process.argv[2] || "update";
const arg = process.argv[3] || "";
const root = findProjectRoot(process.cwd());
const contextFile = path.join(root, "CONTEXT.md");
const agentsFile = path.join(root, "AGENTS.md");

main();

function main() {
  const context = readTextSafe(contextFile);
  if (!context) {
    console.error("CONTEXT.md not found.");
    process.exit(1);
  }

  if (command === "update") {
    updateAgents(context);
    return;
  }

  if (command === "list") {
    process.stdout.write(renderIndex(context));
    return;
  }

  if (command === "section") {
    printSection(context, arg);
    return;
  }

  if (command === "query") {
    queryIndex(context, arg);
    return;
  }

  if (command === "check") {
    checkHarness(context);
    return;
  }

  console.error("Usage: node scripts/context-index.js [update|list|query|section|check] [text]");
  process.exit(1);
}

function updateAgents(context) {
  const current = readTextSafe(agentsFile) || defaultAgents();
  const block = renderIndex(context).trimEnd();
  const next = replaceManagedBlock(current, block);
  fs.writeFileSync(agentsFile, `${next.trimEnd()}\n`);
  console.log(`Updated ${path.relative(root, agentsFile)} from CONTEXT.md.`);
}

function renderIndex(context) {
  const sections = parseSections(context).filter((section) => section.level === 2);
  const lines = [
    "## Context Index",
    START,
    "Generated by `node scripts/context-index.js update`; open only relevant sections.",
    "",
    "- `NOW.md` - read first on start/resume.",
  ];

  for (const section of sections) {
    const childText = section.children.length
      ? ` Sub: ${section.children.map((child) => child.title).join(", ")}.`
      : "";
    lines.push(`- \`CONTEXT.md#${section.anchor}\` - ${describeSection(context, section)}.${childText}`);
  }

  lines.push(END);
  return `${lines.join("\n")}\n`;
}

function replaceManagedBlock(text, block) {
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start !== -1 && end !== -1 && end > start) {
    const prefix = text.slice(0, start);
    const headingMatch = prefix.match(/(?:^|\n)(?:## Context Index\s*\n\s*)+$/u);
    const replaceStart = headingMatch
      ? prefix.length - headingMatch[0].length + (headingMatch[0].startsWith("\n") ? 1 : 0)
      : start;
    const before = text.slice(0, replaceStart).replace(/[ \t]*$/u, "");
    const after = text.slice(end + END.length).replace(/^\s*/u, "\n");
    return `${before}${block}${after}`;
  }
  return `${text.trimEnd()}\n\n${block}`;
}

function defaultAgents() {
  return `# Agent Instructions
<!-- context-harness:schema v3 -->

## Context Contract
- At session start/resume, read \`NOW.md\` first, then use the Context Index below to choose relevant \`CONTEXT.md\` sections.
- Before planning or editing, respect \`CONTEXT.md\` \`## Rules\`.
- If the user teaches a durable term, invariant, workflow, constraint, or
  correction, update \`CONTEXT.md\` before it scrolls away.
- Route task-local findings and decisions to \`PLAN.md\`; durable lessons to
  \`CONTEXT.md\`.
- After updating \`CONTEXT.md\`, run \`node scripts/context-index.js update\`.
- Before ending, update \`NOW.md\` with current focus, blockers, next step, and
  touched files.
`;
}

function checkHarness(context) {
  const failures = [];
  const warnings = [];
  const agents = readTextSafe(agentsFile);
  const now = readTextSafe(path.join(root, "NOW.md"));
  const plan = readTextSafe(path.join(root, "PLAN.md"));

  const requiredSections = [
    "Project",
    "Structure",
    "Rules",
    "Workflow",
    "Language",
    "Relationships",
    "Flagged Ambiguities",
    "Learned Patterns",
  ];

  if (!hasSchema(context)) failures.push("CONTEXT.md is missing a context-harness schema marker.");
  else if (hasLegacySchema(context)) warnings.push("CONTEXT.md uses legacy schema v2.");

  if (!agents.trim()) failures.push("AGENTS.md is missing.");
  else if (!hasSchema(agents)) failures.push("AGENTS.md is missing a context-harness schema marker.");
  else if (hasLegacySchema(agents)) warnings.push("AGENTS.md uses legacy schema v2.");

  if (agents.trim()) {
    const agentLines = agents.trimEnd().split("\n").length;
    const nonIndex = stripIndex(agents);
    if (agentLines > 80) {
      warnings.push(`AGENTS.md has ${agentLines} lines; keep it to the Context Contract plus generated Context Index.`);
    }
    if (looksLikeDetailedOperatingBrief(nonIndex)) {
      warnings.push("AGENTS.md appears to contain durable operating context; move project facts to CONTEXT.md.");
    }
  }

  for (const heading of requiredSections) {
    if (!hasHeading(context, 2, heading)) failures.push(`CONTEXT.md is missing ## ${heading}.`);
  }

  if (agents.trim()) {
    if (!agents.includes(START) || !agents.includes(END)) {
      failures.push("AGENTS.md is missing the generated Context Index block.");
    } else if (!indexIsFresh(agents, context)) {
      failures.push("AGENTS.md Context Index is stale; run `node scripts/context-index.js update`.");
    }
  }

  if (now.trim()) {
    const nowLines = now.trimEnd().split("\n").length;
    if (nowLines > 20) warnings.push(`NOW.md has ${nowLines} lines; consider a Dream/Compact pass.`);
  }

  if (plan.trim()) {
    const planLines = plan.trimEnd().split("\n").length;
    if (planLines > 150) warnings.push(`PLAN.md has ${planLines} lines; consider a Dream/Compact pass.`);
  }

  for (const warning of warnings) console.log(`WARN ${warning}`);
  if (failures.length) {
    for (const failure of failures) console.log(`FAIL ${failure}`);
    process.exit(1);
  }
  console.log("OK context-harness check passed.");
}

function hasSchema(text) {
  return /<!--\s*context-harness:schema\s+v[23]\s*-->/.test(text);
}

function hasLegacySchema(text) {
  return /<!--\s*context-harness:schema\s+v2\s*-->/.test(text);
}

function stripIndex(text) {
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start === -1 || end === -1 || end <= start) return text;
  return `${text.slice(0, start)}${text.slice(end + END.length)}`;
}

function looksLikeDetailedOperatingBrief(text) {
  const durableHeadings = [
    "Current Status",
    "Project Mission",
    "Near-Term Priorities",
    "Guiding Principles",
    "High-Level Timeline",
    "Communication Style",
    "Reusable Templates",
    "Recent Key Achievements",
  ];
  const headingHits = durableHeadings.filter((heading) => hasHeading(text, 2, heading) || hasHeading(text, 3, heading)).length;
  if (headingHits >= 2) return true;

  return /detailed durable project context remains in `?AGENTS\.md`?/i.test(text)
    || /AGENTS\.md.*(detailed|primary).*operating/i.test(text)
    || /comprehensive context for AI agents/i.test(text);
}

function hasHeading(markdown, level, heading) {
  const hashes = "#".repeat(level);
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`^${hashes}\\s+${escaped}\\s*$`, "m").test(markdown);
}

function indexIsFresh(agents, context) {
  const expected = renderIndex(context).trim();
  const start = agents.indexOf(START);
  const end = agents.indexOf(END);
  if (start === -1 || end === -1 || end <= start) return false;
  const headingStart = agents.lastIndexOf("## Context Index", start);
  const actualStart = headingStart === -1 ? start : headingStart;
  const actual = agents.slice(actualStart, end + END.length).trim();
  return actual === expected;
}

function parseSections(context) {
  const sections = [];
  let currentH2 = null;
  for (const line of context.split("\n")) {
    const match = line.match(/^(##|###)\s+(.+?)\s*$/u);
    if (!match) continue;
    const section = {
      level: match[1].length,
      title: match[2].replace(/`/g, ""),
      anchor: anchorFor(match[2]),
      children: [],
    };
    if (section.level === 2) {
      sections.push(section);
      currentH2 = section;
    } else if (section.level === 3 && currentH2) {
      currentH2.children.push(section);
      sections.push(section);
    }
  }
  return sections;
}

function describeSection(context, section) {
  if (PURPOSES[section.title]) return PURPOSES[section.title];
  const body = readSection(context, section.title);
  const first = body
    .split("\n")
    .map((line) => line.trim())
    .find((line) => line && !line.startsWith("<!--") && !line.startsWith("```"));
  return first ? truncate(cleanMarkdown(first), 90) : "context section";
}

function printSection(context, heading) {
  if (!heading) {
    console.error("Provide a section heading.");
    process.exit(1);
  }
  const body = readSection(context, heading);
  if (!body.trim()) {
    console.error(`Section not found: ${heading}`);
    process.exit(1);
  }
  process.stdout.write(`## ${heading}\n${body.trimEnd()}\n`);
}

function queryIndex(context, query) {
  const terms = query
    .toLowerCase()
    .split(/\s+/u)
    .map((term) => term.trim())
    .filter(Boolean);
  if (!terms.length) {
    console.error("Provide a query term.");
    process.exit(1);
  }

  const matches = parseSections(context)
    .filter((section) => section.level === 2)
    .map((section) => {
      const body = readSection(context, section.title);
      const haystack = `${section.title}\n${body}`.toLowerCase();
      return { section, body, hit: terms.every((term) => haystack.includes(term)) };
    })
    .filter((entry) => entry.hit);

  if (!matches.length) {
    console.log("No matching CONTEXT.md sections.");
    return;
  }

  for (const { section, body } of matches) {
    console.log(`- CONTEXT.md#${section.anchor} (${section.title})`);
    const snippet = body
      .split("\n")
      .map((line) => cleanMarkdown(line.trim()))
      .find((line) => line && terms.some((term) => line.toLowerCase().includes(term)));
    if (snippet) console.log(`  ${truncate(snippet, 120)}`);
  }
}

function anchorFor(title) {
  return title
    .toLowerCase()
    .replace(/`/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function cleanMarkdown(line) {
  return line
    .replace(/^[-*]\s+/u, "")
    .replace(/^\d+\.\s+/u, "")
    .replace(/[`*_]/g, "")
    .trim();
}

function truncate(text, max) {
  if (text.length <= max) return text;
  return `${text.slice(0, max - 3).trimEnd()}...`;
}
